//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//
package org.seadatanet.csr.org.isotc211._2005.gco;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractDQElementType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractDQResultType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractDSAggregateType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractEXGeographicExtentType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractMDContentInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractMDIdentificationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractMDSpatialRepresentationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractRSReferenceSystemType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CIAddressType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CICitationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CIContactType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CIDateType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CIOnlineResourceType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CIResponsiblePartyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CISeriesType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CITelephoneType;
import org.seadatanet.csr.org.isotc211._2005.gmd.DQDataQualityType;
import org.seadatanet.csr.org.isotc211._2005.gmd.DQScopeType;
import org.seadatanet.csr.org.isotc211._2005.gmd.DSAssociationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.DSDataSetType;
import org.seadatanet.csr.org.isotc211._2005.gmd.EXExtentType;
import org.seadatanet.csr.org.isotc211._2005.gmd.EXTemporalExtentType;
import org.seadatanet.csr.org.isotc211._2005.gmd.EXVerticalExtentType;
import org.seadatanet.csr.org.isotc211._2005.gmd.LILineageType;
import org.seadatanet.csr.org.isotc211._2005.gmd.LIProcessStepType;
import org.seadatanet.csr.org.isotc211._2005.gmd.LISourceType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDAggregateInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDApplicationSchemaInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDBrowseGraphicType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDConstraintsType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDDigitalTransferOptionsType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDDimensionType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDDistributionType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDDistributorType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDExtendedElementInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDFormatType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDGeometricObjectsType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDIdentifierType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDKeywordsType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDMaintenanceInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDMediumType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDMetadataExtensionInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDMetadataType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDPortrayalCatalogueReferenceType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDRangeDimensionType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDReferenceSystemType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDRepresentativeFractionType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDStandardOrderProcessType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDUsageType;
import org.seadatanet.csr.org.isotc211._2005.gmd.PTFreeTextType;
import org.seadatanet.csr.org.isotc211._2005.gmd.PTLocaleType;
import org.seadatanet.csr.org.isotc211._2005.gmi.AbstractMIGeolocationInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmi.LEAlgorithmType;
import org.seadatanet.csr.org.isotc211._2005.gmi.LEProcessStepReportType;
import org.seadatanet.csr.org.isotc211._2005.gmi.LEProcessingType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIAcquisitionInformationType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIEnvironmentalRecordType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIEventType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIGCPType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIInstrumentType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIObjectiveType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIOperationType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIPlanType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIPlatformPassType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIPlatformType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIRangeElementDescriptionType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIRequestedDateType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MIRequirementType;
import org.seadatanet.csr.org.isotc211._2005.gmi.MXDataFileType;
 import org.seadatanet.csr.org.isotc211._2005.gmx.AbstractCTCatalogueType;
 import org.seadatanet.csr.org.isotc211._2005.gmx.AbstractMXFileType;

/**
 * <p>
 * Java class for AbstractObject_Type complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="AbstractObject_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.isotc211.org/2005/gco}ObjectIdentification"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractObject_Type")
@XmlSeeAlso({
    MIObjectiveType.class,
    EXVerticalExtentType.class,
    EXExtentType.class,
    EXTemporalExtentType.class,
    AbstractEXGeographicExtentType.class,
    MDIdentifierType.class,
    MDReferenceSystemType.class,
    AbstractRSReferenceSystemType.class,
    CIResponsiblePartyType.class,
    CICitationType.class,
    CIAddressType.class,
    CIOnlineResourceType.class,
    CIContactType.class,
    CITelephoneType.class,
    CIDateType.class,
    CISeriesType.class,
    MDDimensionType.class,
    MDGeometricObjectsType.class,
    MDExtendedElementInformationType.class,
    MDMetadataExtensionInformationType.class,
    MDApplicationSchemaInformationType.class,
    MDPortrayalCatalogueReferenceType.class,
    MDConstraintsType.class,
    MDMediumType.class,
    MDDigitalTransferOptionsType.class,
    MDStandardOrderProcessType.class,
    MDDistributorType.class,
    MDDistributionType.class,
    MDFormatType.class,
    MDMaintenanceInformationType.class,
    MDBrowseGraphicType.class,
    AbstractMDIdentificationType.class,
    MDRepresentativeFractionType.class,
    MDUsageType.class,
    MDKeywordsType.class,
    DSAssociationType.class,
    MDAggregateInformationType.class,
    LILineageType.class,
    DQDataQualityType.class,
    DQScopeType.class,
    PTFreeTextType.class,
    PTLocaleType.class,
    TypeNameType.class,
    MemberNameType.class,
    MultiplicityType.class,
    MultiplicityRangeType.class,
    AbstractCTCatalogueType.class,
    AbstractDSAggregateType.class,
    DSDataSetType.class,
    AbstractMXFileType.class,
    MIRequirementType.class,
    MIAcquisitionInformationType.class,
    MIPlanType.class,
    MIOperationType.class,
    MIInstrumentType.class,
    MIPlatformType.class,
    MIEnvironmentalRecordType.class,
    MIEventType.class,
    MIRequestedDateType.class,
    MIPlatformPassType.class,
    MDMetadataType.class,
    LIProcessStepType.class,
    MXDataFileType.class,
    LEProcessingType.class,
    AbstractDQResultType.class,
    LEProcessStepReportType.class,
    LEAlgorithmType.class,
    LISourceType.class,
    AbstractDQElementType.class,
    MIGCPType.class,
    AbstractMIGeolocationInformationType.class,
    AbstractMDSpatialRepresentationType.class,
    MIRangeElementDescriptionType.class,
    MDRangeDimensionType.class,
    AbstractMDContentInformationType.class
})
public abstract class AbstractObjectType implements Serializable {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "uuid")
    protected String uuid;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id != null);
    }

    /**
     * Gets the value of the uuid property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    public boolean isSetUuid() {
        return (this.uuid != null);
    }

}
