//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//


package org.seadatanet.csr.net.opengis.gml;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class NetOpengisGmlAffineCSType
    extends JAXBElement<AffineCSType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml", "AffineCS");

    public NetOpengisGmlAffineCSType(AffineCSType value) {
        super(NAME, ((Class) AffineCSType.class), null, value);
    }

    public NetOpengisGmlAffineCSType() {
        super(NAME, ((Class) AffineCSType.class), null, null);
    }

}
