//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//


package org.seadatanet.csr.org.isotc211._2005.gmi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.seadatanet.csr.org.isotc211._2005.gco.AbstractObjectType;


/**
 * Description: Designations for the measuring instruments and their bands, the platform carrying them, and the mission to which the data contributes - FGDC: Platform_and_Instrument_Identification, Mission_Information - shortName: PltfrmInstId
 * 
 * <p>Java class for MI_AcquisitionInformation_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MI_AcquisitionInformation_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gco}AbstractObject_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="acquisitionRequirement" type="{http://www.isotc211.org/2005/gmi}MI_Requirement_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="objective" type="{http://www.isotc211.org/2005/gmi}MI_Objective_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="instrument" type="{http://www.isotc211.org/2005/gmi}MI_Instrument_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="acquisitionPlan" type="{http://www.isotc211.org/2005/gmi}MI_Plan_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="operation" type="{http://www.isotc211.org/2005/gmi}MI_Operation_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="platform" type="{http://www.isotc211.org/2005/gmi}MI_Platform_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="environmentalConditions" type="{http://www.isotc211.org/2005/gmi}MI_EnvironmentalRecord_PropertyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MI_AcquisitionInformation_Type", propOrder = {
    "acquisitionRequirement",
    "objective",
    "instrument",
    "acquisitionPlan",
    "operation",
    "platform",
    "environmentalConditions"
})
public class MIAcquisitionInformationType
    extends AbstractObjectType
    implements Serializable
{

    protected List<MIRequirementPropertyType> acquisitionRequirement;
    protected List<MIObjectivePropertyType> objective;
    protected List<MIInstrumentPropertyType> instrument;
    protected List<MIPlanPropertyType> acquisitionPlan;
    protected List<MIOperationPropertyType> operation;
    protected List<MIPlatformPropertyType> platform;
    protected MIEnvironmentalRecordPropertyType environmentalConditions;

    /**
     * Gets the value of the acquisitionRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acquisitionRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcquisitionRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIRequirementPropertyType }
     * 
     * 
     */
    public List<MIRequirementPropertyType> getAcquisitionRequirement() {
        if (acquisitionRequirement == null) {
            acquisitionRequirement = new ArrayList<MIRequirementPropertyType>();
        }
        return this.acquisitionRequirement;
    }

    public boolean isSetAcquisitionRequirement() {
        return ((this.acquisitionRequirement!= null)&&(!this.acquisitionRequirement.isEmpty()));
    }

    public void unsetAcquisitionRequirement() {
        this.acquisitionRequirement = null;
    }

    /**
     * Gets the value of the objective property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objective property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjective().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIObjectivePropertyType }
     * 
     * 
     */
    public List<MIObjectivePropertyType> getObjective() {
        if (objective == null) {
            objective = new ArrayList<MIObjectivePropertyType>();
        }
        return this.objective;
    }

    public boolean isSetObjective() {
        return ((this.objective!= null)&&(!this.objective.isEmpty()));
    }

    public void unsetObjective() {
        this.objective = null;
    }

    /**
     * Gets the value of the instrument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instrument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstrument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIInstrumentPropertyType }
     * 
     * 
     */
    public List<MIInstrumentPropertyType> getInstrument() {
        if (instrument == null) {
            instrument = new ArrayList<MIInstrumentPropertyType>();
        }
        return this.instrument;
    }

    public boolean isSetInstrument() {
        return ((this.instrument!= null)&&(!this.instrument.isEmpty()));
    }

    public void unsetInstrument() {
        this.instrument = null;
    }

    /**
     * Gets the value of the acquisitionPlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acquisitionPlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcquisitionPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIPlanPropertyType }
     * 
     * 
     */
    public List<MIPlanPropertyType> getAcquisitionPlan() {
        if (acquisitionPlan == null) {
            acquisitionPlan = new ArrayList<MIPlanPropertyType>();
        }
        return this.acquisitionPlan;
    }

    public boolean isSetAcquisitionPlan() {
        return ((this.acquisitionPlan!= null)&&(!this.acquisitionPlan.isEmpty()));
    }

    public void unsetAcquisitionPlan() {
        this.acquisitionPlan = null;
    }

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIOperationPropertyType }
     * 
     * 
     */
    public List<MIOperationPropertyType> getOperation() {
        if (operation == null) {
            operation = new ArrayList<MIOperationPropertyType>();
        }
        return this.operation;
    }

    public boolean isSetOperation() {
        return ((this.operation!= null)&&(!this.operation.isEmpty()));
    }

    public void unsetOperation() {
        this.operation = null;
    }

    /**
     * Gets the value of the platform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIPlatformPropertyType }
     * 
     * 
     */
    public List<MIPlatformPropertyType> getPlatform() {
        if (platform == null) {
            platform = new ArrayList<MIPlatformPropertyType>();
        }
        return this.platform;
    }

    public boolean isSetPlatform() {
        return ((this.platform!= null)&&(!this.platform.isEmpty()));
    }

    public void unsetPlatform() {
        this.platform = null;
    }

    /**
     * Gets the value of the environmentalConditions property.
     * 
     * @return
     *     possible object is
     *     {@link MIEnvironmentalRecordPropertyType }
     *     
     */
    public MIEnvironmentalRecordPropertyType getEnvironmentalConditions() {
        return environmentalConditions;
    }

    /**
     * Sets the value of the environmentalConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIEnvironmentalRecordPropertyType }
     *     
     */
    public void setEnvironmentalConditions(MIEnvironmentalRecordPropertyType value) {
        this.environmentalConditions = value;
    }

    public boolean isSetEnvironmentalConditions() {
        return (this.environmentalConditions!= null);
    }

}
