//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//


package org.seadatanet.csr.org.isotc211._2005.gmi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.seadatanet.csr.org.isotc211._2005.gco.AbstractObjectType;
import org.seadatanet.csr.org.isotc211._2005.gco.DateTimePropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDIdentifierPropertyType;


/**
 * Description: identification of a significant collection point within an operation - shortName: Event
 * 
 * <p>Java class for MI_Event_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MI_Event_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gco}AbstractObject_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://www.isotc211.org/2005/gmd}MD_Identifier_PropertyType"/&gt;
 *         &lt;element name="trigger" type="{http://www.isotc211.org/2005/gmi}MI_TriggerCode_PropertyType"/&gt;
 *         &lt;element name="context" type="{http://www.isotc211.org/2005/gmi}MI_ContextCode_PropertyType"/&gt;
 *         &lt;element name="sequence" type="{http://www.isotc211.org/2005/gmi}MI_SequenceCode_PropertyType"/&gt;
 *         &lt;element name="time" type="{http://www.isotc211.org/2005/gco}DateTime_PropertyType"/&gt;
 *         &lt;element name="expectedObjective" type="{http://www.isotc211.org/2005/gmi}MI_Objective_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="relatedSensor" type="{http://www.isotc211.org/2005/gmi}MI_Instrument_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="relatedPass" type="{http://www.isotc211.org/2005/gmi}MI_PlatformPass_PropertyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MI_Event_Type", propOrder = {
    "identifier",
    "trigger",
    "context",
    "sequence",
    "time",
    "expectedObjective",
    "relatedSensor",
    "relatedPass"
})
public class MIEventType
    extends AbstractObjectType
    implements Serializable
{

    @XmlElement(required = true)
    protected MDIdentifierPropertyType identifier;
    @XmlElement(required = true)
    protected MITriggerCodePropertyType trigger;
    @XmlElement(required = true)
    protected MIContextCodePropertyType context;
    @XmlElement(required = true)
    protected MISequenceCodePropertyType sequence;
    @XmlElement(required = true)
    protected DateTimePropertyType time;
    protected List<MIObjectivePropertyType> expectedObjective;
    protected List<MIInstrumentPropertyType> relatedSensor;
    protected MIPlatformPassPropertyType relatedPass;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link MDIdentifierPropertyType }
     *     
     */
    public MDIdentifierPropertyType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDIdentifierPropertyType }
     *     
     */
    public void setIdentifier(MDIdentifierPropertyType value) {
        this.identifier = value;
    }

    public boolean isSetIdentifier() {
        return (this.identifier!= null);
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link MITriggerCodePropertyType }
     *     
     */
    public MITriggerCodePropertyType getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link MITriggerCodePropertyType }
     *     
     */
    public void setTrigger(MITriggerCodePropertyType value) {
        this.trigger = value;
    }

    public boolean isSetTrigger() {
        return (this.trigger!= null);
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link MIContextCodePropertyType }
     *     
     */
    public MIContextCodePropertyType getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIContextCodePropertyType }
     *     
     */
    public void setContext(MIContextCodePropertyType value) {
        this.context = value;
    }

    public boolean isSetContext() {
        return (this.context!= null);
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link MISequenceCodePropertyType }
     *     
     */
    public MISequenceCodePropertyType getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISequenceCodePropertyType }
     *     
     */
    public void setSequence(MISequenceCodePropertyType value) {
        this.sequence = value;
    }

    public boolean isSetSequence() {
        return (this.sequence!= null);
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimePropertyType }
     *     
     */
    public DateTimePropertyType getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimePropertyType }
     *     
     */
    public void setTime(DateTimePropertyType value) {
        this.time = value;
    }

    public boolean isSetTime() {
        return (this.time!= null);
    }

    /**
     * Gets the value of the expectedObjective property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expectedObjective property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpectedObjective().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIObjectivePropertyType }
     * 
     * 
     */
    public List<MIObjectivePropertyType> getExpectedObjective() {
        if (expectedObjective == null) {
            expectedObjective = new ArrayList<MIObjectivePropertyType>();
        }
        return this.expectedObjective;
    }

    public boolean isSetExpectedObjective() {
        return ((this.expectedObjective!= null)&&(!this.expectedObjective.isEmpty()));
    }

    public void unsetExpectedObjective() {
        this.expectedObjective = null;
    }

    /**
     * Gets the value of the relatedSensor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedSensor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedSensor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIInstrumentPropertyType }
     * 
     * 
     */
    public List<MIInstrumentPropertyType> getRelatedSensor() {
        if (relatedSensor == null) {
            relatedSensor = new ArrayList<MIInstrumentPropertyType>();
        }
        return this.relatedSensor;
    }

    public boolean isSetRelatedSensor() {
        return ((this.relatedSensor!= null)&&(!this.relatedSensor.isEmpty()));
    }

    public void unsetRelatedSensor() {
        this.relatedSensor = null;
    }

    /**
     * Gets the value of the relatedPass property.
     * 
     * @return
     *     possible object is
     *     {@link MIPlatformPassPropertyType }
     *     
     */
    public MIPlatformPassPropertyType getRelatedPass() {
        return relatedPass;
    }

    /**
     * Sets the value of the relatedPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIPlatformPassPropertyType }
     *     
     */
    public void setRelatedPass(MIPlatformPassPropertyType value) {
        this.relatedPass = value;
    }

    public boolean isSetRelatedPass() {
        return (this.relatedPass!= null);
    }

}
