//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//


package org.seadatanet.csr.org.isotc211._2005.gmi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDGeorectifiedType;


/**
 * Description: extends georectified grid description to include associated checkpoints - shortName: IGeorect
 * 
 * <p>Java class for MI_Georectified_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MI_Georectified_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gmd}MD_Georectified_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="checkPoint" type="{http://www.isotc211.org/2005/gmi}MI_GCP_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="geolocationIdentification" type="{http://www.isotc211.org/2005/gmi}MI_GCPCollection_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MI_Georectified_Type", propOrder = {
    "checkPoint",
    "geolocationIdentification"
})
public class MIGeorectifiedType
    extends MDGeorectifiedType
    implements Serializable
{

    protected List<MIGCPPropertyType> checkPoint;
    protected List<MIGCPCollectionPropertyType> geolocationIdentification;

    /**
     * Gets the value of the checkPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checkPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCheckPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIGCPPropertyType }
     * 
     * 
     */
    public List<MIGCPPropertyType> getCheckPoint() {
        if (checkPoint == null) {
            checkPoint = new ArrayList<MIGCPPropertyType>();
        }
        return this.checkPoint;
    }

    public boolean isSetCheckPoint() {
        return ((this.checkPoint!= null)&&(!this.checkPoint.isEmpty()));
    }

    public void unsetCheckPoint() {
        this.checkPoint = null;
    }

    /**
     * Gets the value of the geolocationIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geolocationIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeolocationIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIGCPCollectionPropertyType }
     * 
     * 
     */
    public List<MIGCPCollectionPropertyType> getGeolocationIdentification() {
        if (geolocationIdentification == null) {
            geolocationIdentification = new ArrayList<MIGCPCollectionPropertyType>();
        }
        return this.geolocationIdentification;
    }

    public boolean isSetGeolocationIdentification() {
        return ((this.geolocationIdentification!= null)&&(!this.geolocationIdentification.isEmpty()));
    }

    public void unsetGeolocationIdentification() {
        this.geolocationIdentification = null;
    }

}
