//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//
package org.seadatanet.csr.org.isotc211._2005.gmi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDMetadataType;

/**
 * Description: Root entity that defines information about imagery or gridded
 * data - shortName: IMetadata
 *
 * <p>
 * Java class for MI_Metadata_Type complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="MI_Metadata_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gmd}MD_Metadata_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="acquisitionInformation" type="{http://www.isotc211.org/2005/gmi}MI_AcquisitionInformation_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MI_Metadata_Type", propOrder = {
    "acquisitionInformation"
})
public class MIMetadataType
        extends MDMetadataType
        implements Serializable {

    protected List<MIAcquisitionInformationPropertyType> acquisitionInformation;

    /**
     * Gets the value of the acquisitionInformation property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the acquisitionInformation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcquisitionInformation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIAcquisitionInformationPropertyType }
     *
     *
     */
    public List<MIAcquisitionInformationPropertyType> getAcquisitionInformation() {
        if (acquisitionInformation == null) {
            acquisitionInformation = new ArrayList<MIAcquisitionInformationPropertyType>();
        }
        return this.acquisitionInformation;
    }

    public boolean isSetAcquisitionInformation() {
        return ((this.acquisitionInformation != null) && (!this.acquisitionInformation.isEmpty()));
    }

    public void unsetAcquisitionInformation() {
        this.acquisitionInformation = null;
    }

}
