//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//


package org.seadatanet.csr.org.isotc211._2005.gmi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.seadatanet.csr.org.isotc211._2005.gco.AbstractObjectType;
import org.seadatanet.csr.org.isotc211._2005.gco.DateTimePropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CICitationPropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.CIResponsiblePartyPropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDIdentifierPropertyType;


/**
 * Description: requirement to be satisfied by the planned data acquisition - shortName: Requirement
 * 
 * <p>Java class for MI_Requirement_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MI_Requirement_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gco}AbstractObject_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="citation" type="{http://www.isotc211.org/2005/gmd}CI_Citation_PropertyType" minOccurs="0"/&gt;
 *         &lt;element name="identifier" type="{http://www.isotc211.org/2005/gmd}MD_Identifier_PropertyType"/&gt;
 *         &lt;element name="requestor" type="{http://www.isotc211.org/2005/gmd}CI_ResponsibleParty_PropertyType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="recipient" type="{http://www.isotc211.org/2005/gmd}CI_ResponsibleParty_PropertyType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="priority" type="{http://www.isotc211.org/2005/gmi}MI_PriorityCode_PropertyType"/&gt;
 *         &lt;element name="requestedDate" type="{http://www.isotc211.org/2005/gmi}MI_RequestedDate_PropertyType"/&gt;
 *         &lt;element name="expiryDate" type="{http://www.isotc211.org/2005/gco}DateTime_PropertyType"/&gt;
 *         &lt;element name="satisifiedPlan" type="{http://www.isotc211.org/2005/gmi}MI_Plan_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MI_Requirement_Type", propOrder = {
    "citation",
    "identifier",
    "requestor",
    "recipient",
    "priority",
    "requestedDate",
    "expiryDate",
    "satisifiedPlan"
})
public class MIRequirementType
    extends AbstractObjectType
    implements Serializable
{

    protected CICitationPropertyType citation;
    @XmlElement(required = true)
    protected MDIdentifierPropertyType identifier;
    @XmlElement(required = true)
    protected List<CIResponsiblePartyPropertyType> requestor;
    @XmlElement(required = true)
    protected List<CIResponsiblePartyPropertyType> recipient;
    @XmlElement(required = true)
    protected MIPriorityCodePropertyType priority;
    @XmlElement(required = true)
    protected MIRequestedDatePropertyType requestedDate;
    @XmlElement(required = true)
    protected DateTimePropertyType expiryDate;
    protected List<MIPlanPropertyType> satisifiedPlan;

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link CICitationPropertyType }
     *     
     */
    public CICitationPropertyType getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICitationPropertyType }
     *     
     */
    public void setCitation(CICitationPropertyType value) {
        this.citation = value;
    }

    public boolean isSetCitation() {
        return (this.citation!= null);
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link MDIdentifierPropertyType }
     *     
     */
    public MDIdentifierPropertyType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDIdentifierPropertyType }
     *     
     */
    public void setIdentifier(MDIdentifierPropertyType value) {
        this.identifier = value;
    }

    public boolean isSetIdentifier() {
        return (this.identifier!= null);
    }

    /**
     * Gets the value of the requestor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CIResponsiblePartyPropertyType }
     * 
     * 
     */
    public List<CIResponsiblePartyPropertyType> getRequestor() {
        if (requestor == null) {
            requestor = new ArrayList<CIResponsiblePartyPropertyType>();
        }
        return this.requestor;
    }

    public boolean isSetRequestor() {
        return ((this.requestor!= null)&&(!this.requestor.isEmpty()));
    }

    public void unsetRequestor() {
        this.requestor = null;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CIResponsiblePartyPropertyType }
     * 
     * 
     */
    public List<CIResponsiblePartyPropertyType> getRecipient() {
        if (recipient == null) {
            recipient = new ArrayList<CIResponsiblePartyPropertyType>();
        }
        return this.recipient;
    }

    public boolean isSetRecipient() {
        return ((this.recipient!= null)&&(!this.recipient.isEmpty()));
    }

    public void unsetRecipient() {
        this.recipient = null;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link MIPriorityCodePropertyType }
     *     
     */
    public MIPriorityCodePropertyType getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIPriorityCodePropertyType }
     *     
     */
    public void setPriority(MIPriorityCodePropertyType value) {
        this.priority = value;
    }

    public boolean isSetPriority() {
        return (this.priority!= null);
    }

    /**
     * Gets the value of the requestedDate property.
     * 
     * @return
     *     possible object is
     *     {@link MIRequestedDatePropertyType }
     *     
     */
    public MIRequestedDatePropertyType getRequestedDate() {
        return requestedDate;
    }

    /**
     * Sets the value of the requestedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIRequestedDatePropertyType }
     *     
     */
    public void setRequestedDate(MIRequestedDatePropertyType value) {
        this.requestedDate = value;
    }

    public boolean isSetRequestedDate() {
        return (this.requestedDate!= null);
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimePropertyType }
     *     
     */
    public DateTimePropertyType getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimePropertyType }
     *     
     */
    public void setExpiryDate(DateTimePropertyType value) {
        this.expiryDate = value;
    }

    public boolean isSetExpiryDate() {
        return (this.expiryDate!= null);
    }

    /**
     * Gets the value of the satisifiedPlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the satisifiedPlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSatisifiedPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIPlanPropertyType }
     * 
     * 
     */
    public List<MIPlanPropertyType> getSatisifiedPlan() {
        if (satisifiedPlan == null) {
            satisifiedPlan = new ArrayList<MIPlanPropertyType>();
        }
        return this.satisifiedPlan;
    }

    public boolean isSetSatisifiedPlan() {
        return ((this.satisifiedPlan!= null)&&(!this.satisifiedPlan.isEmpty()));
    }

    public void unsetSatisifiedPlan() {
        this.satisifiedPlan = null;
    }

}
