//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.09.29 at 03:54:02 PM CEST 
//


package org.seadatanet.csr.org.isotc211._2005.gmi;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.seadatanet.csr.org.isotc211._2005.gmd.AbstractDQResultType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDCoverageDescriptionPropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDFormatPropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDSpatialRepresentationPropertyType;
import org.seadatanet.csr.org.isotc211._2005.gmd.MDSpatialRepresentationTypeCodePropertyType;


/**
 * Description: Result of a data quality measure organising the measured values as a coverage - shortName: CoverageResult
 * 
 * <p>Java class for QE_CoverageResult_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QE_CoverageResult_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gmd}AbstractDQ_Result_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="spatialRepresentationType" type="{http://www.isotc211.org/2005/gmd}MD_SpatialRepresentationTypeCode_PropertyType"/&gt;
 *         &lt;element name="resultSpatialRepresentation" type="{http://www.isotc211.org/2005/gmd}MD_SpatialRepresentation_PropertyType"/&gt;
 *         &lt;element name="resultContentDescription" type="{http://www.isotc211.org/2005/gmd}MD_CoverageDescription_PropertyType"/&gt;
 *         &lt;element name="resultFormat" type="{http://www.isotc211.org/2005/gmd}MD_Format_PropertyType"/&gt;
 *         &lt;element name="resultFile" type="{http://www.isotc211.org/2005/gmi}MX_DataFile_PropertyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QE_CoverageResult_Type", propOrder = {
    "spatialRepresentationType",
    "resultSpatialRepresentation",
    "resultContentDescription",
    "resultFormat",
    "resultFile"
})
public class QECoverageResultType
    extends AbstractDQResultType
    implements Serializable
{

    @XmlElement(required = true)
    protected MDSpatialRepresentationTypeCodePropertyType spatialRepresentationType;
    @XmlElement(required = true)
    protected MDSpatialRepresentationPropertyType resultSpatialRepresentation;
    @XmlElement(required = true)
    protected MDCoverageDescriptionPropertyType resultContentDescription;
    @XmlElement(required = true)
    protected MDFormatPropertyType resultFormat;
    @XmlElement(required = true)
    protected MXDataFilePropertyType resultFile;

    /**
     * Gets the value of the spatialRepresentationType property.
     * 
     * @return
     *     possible object is
     *     {@link MDSpatialRepresentationTypeCodePropertyType }
     *     
     */
    public MDSpatialRepresentationTypeCodePropertyType getSpatialRepresentationType() {
        return spatialRepresentationType;
    }

    /**
     * Sets the value of the spatialRepresentationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDSpatialRepresentationTypeCodePropertyType }
     *     
     */
    public void setSpatialRepresentationType(MDSpatialRepresentationTypeCodePropertyType value) {
        this.spatialRepresentationType = value;
    }

    public boolean isSetSpatialRepresentationType() {
        return (this.spatialRepresentationType!= null);
    }

    /**
     * Gets the value of the resultSpatialRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link MDSpatialRepresentationPropertyType }
     *     
     */
    public MDSpatialRepresentationPropertyType getResultSpatialRepresentation() {
        return resultSpatialRepresentation;
    }

    /**
     * Sets the value of the resultSpatialRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDSpatialRepresentationPropertyType }
     *     
     */
    public void setResultSpatialRepresentation(MDSpatialRepresentationPropertyType value) {
        this.resultSpatialRepresentation = value;
    }

    public boolean isSetResultSpatialRepresentation() {
        return (this.resultSpatialRepresentation!= null);
    }

    /**
     * Gets the value of the resultContentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MDCoverageDescriptionPropertyType }
     *     
     */
    public MDCoverageDescriptionPropertyType getResultContentDescription() {
        return resultContentDescription;
    }

    /**
     * Sets the value of the resultContentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCoverageDescriptionPropertyType }
     *     
     */
    public void setResultContentDescription(MDCoverageDescriptionPropertyType value) {
        this.resultContentDescription = value;
    }

    public boolean isSetResultContentDescription() {
        return (this.resultContentDescription!= null);
    }

    /**
     * Gets the value of the resultFormat property.
     * 
     * @return
     *     possible object is
     *     {@link MDFormatPropertyType }
     *     
     */
    public MDFormatPropertyType getResultFormat() {
        return resultFormat;
    }

    /**
     * Sets the value of the resultFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDFormatPropertyType }
     *     
     */
    public void setResultFormat(MDFormatPropertyType value) {
        this.resultFormat = value;
    }

    public boolean isSetResultFormat() {
        return (this.resultFormat!= null);
    }

    /**
     * Gets the value of the resultFile property.
     * 
     * @return
     *     possible object is
     *     {@link MXDataFilePropertyType }
     *     
     */
    public MXDataFilePropertyType getResultFile() {
        return resultFile;
    }

    /**
     * Sets the value of the resultFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link MXDataFilePropertyType }
     *     
     */
    public void setResultFile(MXDataFilePropertyType value) {
        this.resultFile = value;
    }

    public boolean isSetResultFile() {
        return (this.resultFile!= null);
    }

}
